"""empty message

Revision ID: 8ed6f05d4868
Revises: c7364c5bd46b
Create Date: 2025-06-08 10:58:31.098420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed6f05d4868'
down_revision = 'c7364c5bd46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'column', ['column_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('column_id')

    # ### end Alembic commands ###
